<?php
/**
 * @file
 * Code for the Twitter Tweet feature.
 */

include_once('twitter_tweet.features.inc');
include_once('theme/twitter_tweet.theme.inc');


/**
 * Note: hook_node_validate() is not called when Tweets are imported 
 * from Twitter via Feeds module.
 * 
 * Feeds saves tweet nodes by calling node_save(). There is no 
 * opportunity to validate these nodes before node_saved() gets called.
 * node_save() invokes hook_node_presave(), do any "validation" stuff there.
 * Unfortunately, this limits our ability to prevent importing nodes that would 
 * normally not make it through validation. 
 * @todo This might be able to be handled with a custom Feeds processor.
 * @todo The other option is to have some sort of queue for (manually?) processing bad 
 *  nodes after they've been imported.
 * 
 */

/**
 * Implements hook_node_presave().
 *
 * Tag tweets with Twitter tags (taxonomy terms belonging to the vocabulary
 * Twitter Tags).
 * 
 */
function twitter_tweet_node_presave($node) {
  if ($node->type == 'tweet') {
    $original_tweet = $node->field_tweet_original['und'][0]['value'];

    // Add taxonomy terms to Twitter Tags vocabulary.
    // Pull tags out of tweet.
    $tags = twitter_tweet_get_tags($original_tweet);
    // Now perpare terms as taxonomy terms.
    if (!empty($tags)) {
      $tags = twitter_tweet_save_tags($tags);
    }
    // Add terms to node.
    $node->field_twitter_tags['und'] = $tags;

  }
}


/**
 * Wrapper function for variable_set().
 *
 * @param $tags 
 *    $tags['name'] = array('types', 'go', 'here');
 *    e.g. 
 *    $tags['#example'] = array('hashtag', 'x', 'y', 'z');
 *    $tags['@jane'] = array('mention', 'a', 'b', 'c');
 */
function twitter_tweet_set_tags($tags) {
  variable_set('twitter_tags', $tags);
}
/**
 * @param $original_tweet
 *  String, original Twitter tweet.
 *
 * @return $tweet
 *  String with punctuation that breaks Twitter hashtags and mentions replaced with 
 *  spaces.
 */
function twitter_tweet_replace_punctuation($original_tweet) {
  // Punctuation marks, except underscore, end hashtag wherever punctuation occurs.
  // Replace this punctuation with spaces, so it's easy to explode and create taxonomy
  // terms corresponding with actual Twitter hashtags and user mentions.
  // e.g. on Twitter #this-breaks creates a hashtag called #this.
  $chars = array();
  $chars['find'] = array(
    '-',"'",'.',':',';',
    '~','`','!','$','%','^',
    '&','*','(',')','+','=','<','>',
    '/','?',',','[','{',']','}','|','\\',
  );
  // Create a replacement for each character in the $chars['find'] array.
  foreach($chars as $char) {
    $chars['replace'] = ' ';
  }
  $tweet = str_replace($chars['find'], $chars['replace'], $original_tweet);
  // Check for rogue @ or # symbols standing alone.
  $tweet = str_replace(' # ', ' ', $tweet);
  $tweet = str_replace(' @ ', ' ', $tweet);
  // Get rid of empty white space and double spaces, otherwise
  // explode() won't work correctly.
  $tweet = trim($tweet);
  $tweet = str_replace('  ', ' ', $tweet);

  return $tweet;
}

/**
 * @param $word
 *  string
 *
 * @return $word
 *  string with punctuation that breaks hashtags and user references filtered out.
 *
 * @todo Is this still useful or used anywhere? Remove?
 */
function twitter_tweet_filter_punctuation($word) {
  // Punctuation marks, except underscore, end hashtag wherever punctuation occurs.
  // Filter out stuff that breaks Twitter hashtags, so the taxonomy
  // terms match real Twitter hashtags.
  // e.g. on Twitter #this-breaks creates a hashtag called #this.
  $chars = array(
    '@','#', // Note: if ($position = strpos($word, $char)) evaluates false below,
             // so this doesn't break hashtags and user refrences beginning with 
             // @ or #.
    '-',"'",'.',':',';',
    '~','`','!','$','%','^',
    '&','*','(',')','+','=','<','>',
    '/','?',',','[','{',']','}','|','\\',
  );
  foreach($chars as $char) {
    if ($position = strpos($word, $char)) {
      $word = substr($word, 0, $position);
    }
  }

  return $word; 
}

/**
 * @param $original_tweet
 *  String. Twitter tweet.
 * 
 * @return 
 *  array('#tag1', '@tag2', '#tagN');
 */
function twitter_tweet_get_tags($original_tweet) {
  // Pull tags out of tweet and return those.
  // Replace punctuation with spaces.
  $tweet = twitter_tweet_replace_punctuation($original_tweet);
  $tags = array();

  $words = explode(' ', $tweet);
  foreach($words as $word) {
    if (substr($word, 0, 1) == '#' || substr($word, 0, 1) == '@') {
      $tags[] = $word;
    } 
  }

  return $tags;
}

/**
 * @param $tags
 *  $tags array returned by twitter_tweet_get_tags().
 *  Like this: array('#tag1', '@tag2', '#tagN');
 * 
 * @return $value
 *  Array of taxonomy term arrays.
 *
 * @see taxonomy_autocomplete_validate().
 * @see taxonomy_field_presave().
 */
function twitter_tweet_save_tags($tags) {
  $value = array();

  // Collect candidate vocabularies.
  $vocabularies = array();
  if ($vocabulary = taxonomy_vocabulary_machine_name_load('twitter_tags')) {
    $vocabularies[$vocabulary->vid] = $vocabulary;
  }

  // Translate term names into actual terms.
  //$typed_terms = drupal_explode_tags($tags);
  foreach ($tags as $tag_name) {
    // See if the term exists and return the tid;
    // otherwise, create a new term for insert/update.
    if ($possibilities = taxonomy_term_load_multiple(array(), array('name' => trim($tag_name), 'vid' => array_keys($vocabularies)))) {
      $term = array_pop($possibilities);
    }
    else {
      $vocabulary = reset($vocabularies);
      $term = array(
        'vid' => $vocabulary->vid,
        'name' => $tag_name,
        'vocabulary_machine_name' => $vocabulary->machine_name,
      );
      $term = (object)$term;
      taxonomy_term_save($term);
    }
    $value[] = (array)$term;
  }

  return $value;
}

/**
 * @param $tag_types
 *  Array of tag types like this: array('hashtag', 'x', 'y', 'z').
 * 
 * @return $types
 *  An array of taxonomy term arrays ready to be saved 
 *  in a tweet's field_twitter_tag_type.
 */
function twitter_tweet_save_tag_types($tag_types) {
  $types = array();

  // Collect candidate vocabularies.
  $vocabularies = array();
  if ($vocabulary = taxonomy_vocabulary_machine_name_load('twitter_tag_types')) {
    $vocabularies[$vocabulary->vid] = $vocabulary;
  }

  // Translate term names into actual terms.
  foreach ($tag_types as $type) {
    // See if the term exists and return the tid;
    // otherwise, create a new term for insert/update.
    if ($possibilities = taxonomy_term_load_multiple(array(), array('name' => trim($type), 'vid' => array_keys($vocabularies)))) {
      $term = array_pop($possibilities);
    }
    else {
      $vocabulary = reset($vocabularies);
      $term = array(
        'vid' => $vocabulary->vid,
        'name' => $type,
        'vocabulary_machine_name' => $vocabulary->machine_name,
      );
      $term = (object) $term;
      taxonomy_term_save($term);
      $term = (array) $term;
    }
    $types[] = (array)$term;
  }

  return $types;
}

/**
 * Twitter Tags have a taxonomy field called Twitter Tag Type.
 * This function takes a Twitter tag and returns it's types.
 * Standard types include "hashtag" and "mention". Other modules
 * can add their own Twitter tag types.
 * 
 * @param $param
 *  Integer, term id of a Twitter tag.
 *   Or
 *  Object, Twitter Tag term object.
 * 
 * @return
 *  Array $tag_types = array( tid => 'tag type name' );
 */
function twitter_tweet_get_tag_types($param) {
  $tag_types = array();
  $tids = array();

  if (is_object($param)) {
    $tag = $param;  
  }
  else if (is_numeric($param)) {
    $tid = $param;   
    $tag = taxonomy_term_load($tid);
  }

  if (property_exists($tag, 'field_twitter_tag_types') 
  && isset($tag->field_twitter_tag_types)) {
    foreach ($tag->field_twitter_tag_types as $types) {
      foreach ($types as $type) {
        $tids[] = $type['tid'];
      }
      $tag_types = taxonomy_term_load_multiple($tids);
      foreach ($tag_types as $tid => $obj) {
        $tag_types[$tid] = $obj->name;  
      }
    }

  return $tag_types;
  }
  else {
    return FALSE;  
  }
}

/**
 * @param $term
 *  Taxonomy term object.
 * 
 * @return 
 *  String for alias to be used in $term->path['alias'].
 *
 * @todo Note: It seems like it might be cleaner to handle this with theming, 
 *  by changing the term url, but taxonomy system's preprocess functions and 
 *  theme overrides aren't firing for some reason. 
 */
function _twitter_tweet_term_alias($term) {
  $alias = '';

  if (substr($term->name, 0, 1) == '#') {
    $alias = t('hashtag') . '/' . $term->tid;
  }
  else if (substr($term->name, 0, 1) == '@') {
    $alias = t('mention') . '/' . $term->tid;
  }
  else {
    return FALSE;  
  }

  // Give modules an opportunity to modify the path alias.
  // TODO add error handling incase nobody implements hooks.
  if ($aliases = module_invoke_all('twitter_tweet_twitter_tag_alias_alter', $term, $alias)) {
    $alias = $aliases[0]; 
  }

  return $alias;
}
