<?php
/**
 * @file
 * Code for the Twitter Tweet feature.
 */

include_once('twitter_tweet.features.inc');

/**
 * Implements hook_node_validate().
 *
 * Note: Tweets are imported from Twitter via Feeds module.
 * Feeds saves tweet nodes by calling node_save(). There is no 
 * opportunity to validate these nodes before node_saved() gets called.
 */
/*
function twitter_tweet_node_validate($node, $form, &$form_state) {
}
// */

/**
 * Implements hook_node_presave().
 *
 * Note: 
 */
function twitter_tweet_node_presave($node) {
  if ($node->type == 'tweet') {
//dsm($node);  
    // Store references to twitter users and hashtags 
    // as taxonomy terms.
  }
}

/**
 * Implements hook_field_presave().
 */
/*
function twitter_tweet_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
   dsm('calling hook_field_presave');
   dsm($entity_type, 'entity_type');
   dsm($entity, 'entity');
   dsm($field, 'field');
   dsm($instance, 'instance');
   dsm($items, 'items'); 
 }
// */
